---
- name: Ensure locales is installed
  apt:
    name: "locales"
    state: "present"

- name: Configure locales
  locale_gen:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ locales }}"
